cyIntel/cyIntel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page),
]

cyIntel/reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.subject_list, name='subject_list'),
    url(r'(?P<pk>\d+)/',views.subject_reports, name='subject_reports'),
    
]	

cyIntel/reports/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Subject(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    
    def __str__(self):
        return self.title

class Report(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    date = models.DateField(auto_now=False)
    order = models.IntegerField(default=0)
    subject = models.ForeignKey(Subject)
    content = models.TextField(blank=True, default='')
    
    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('reports:subject_reports', kwargs={'pk':self.pk})

cyIntel/cyIntel/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home_page(request):
	return render(request, 'home.html')
	

cyIntel/reports/views.py
from django.shortcuts import render

from . import models

def subject_list(request):
	'''Lists all available subjects'''
	subject_list = models.Subject.objects.all()
	return render(request, 'reports/subject_list.html',
		{'subject_list': subject_list})

def subject_reports(request, pk):
	'''Show all or a selected date range of
	reports for a given subject'''
	start_date = request.GET.get('start_date')
	end_date = request.GET.get('end_date')
	if end_date:
		reports = models.Report.objects.filter(
		date__range=[start_date, end_date], subject=pk)
	else:
		reports = models.Report.objects.filter(subject=pk)
	return render(request, 'reports/subject_reports.html',
		{'reports': reports})

cyIntel/reports/templates/reports/layout.html
{% extends "layout.html" %}

{% block content %}
	
	{{ block.super }}


	<form method="GET" action="{% url 'reports:report_search' %}">

		{% csrf_token %}
		Enter a start date:<br>
		<input type="date" name="start_date"><br><br>

		Enter an end date:<br>
		<input type="date" name="end_date"><br><br>

		{% block search_form %}{% endblock %}
		<input type="submit"> 

	</form>
	
 
{% endblock %}

cyIntel/reports/templates/reports/report_detail.html
{% extends "layout.html" %}

{% block title %}Report Detail{% endblock %}

{% block content %}
	{% for report in reports %}
		<h2>{{ report.title }}</h2>
		<p>{{ report.created_at }}</p>
		<p>{{ report.content }}</p>
	{% endfor %}
{% endblock %}

cyIntel/reports/templates/reports/subject_list.html
{% extends "layout.html" %}


{% block title %}All{% endblock %}


{% block content %}

    {%  for subject in subject_list %}

        <h2>{{ subject.title }}</h2>
        <p><a href="{% url 'reports:subject_reports' pk=subject.pk %}">[see all]</a></p>

        {{ subject.description }}
        <form method="GET" action="{% url 'reports:subject_reports' pk=subject.pk %}">

			{% csrf_token %}
			Enter a start date:<br>
			<input type="date" name="start_date"><br><br>

			Enter an end date:<br>
			<input type="date" name="end_date"><br><br>

			<input type="submit"> 

		</form>
		<br>

    {% endfor %}

{% endblock %}

cyIntel/reports/templates/reports/subject_reports.html
{% extends "layout.html" %}


{% block title %}Report Detail{% endblock %}


{% block content %}

	{{ block.super }}

	{% for report in reports %}

		<h2>{{ report.title }}</h2>
		<h4>{{ report.subject }}</h4>
		<p>{{ report.date }}</p>
		<p>{{ report.content }}</p>

	{% endfor %}

{% endblock %}

cyIntel/templates/home.html
{% extends "layout.html" %}



{% block content %}
	<h1>CyIntel</h1>
	<h2><a href="{% url 'reports:subject_list' %}">Subjects</a></h2>
{% endblock content %}

cyIntel/templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{{ page_title|default:"" }} | CI{% endblock %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block content %}{% endblock content %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>